### ISSUE TITLE
Windows 11 bass.dll isue

### ISSUE THREAD

**Issue by MassShoes** [ophthalmos/NetRadio#1]
When I try to run NetRadio on a Winows 11 OS I get this error:
This application failed to start because bass. dll was not found. Re-installing the application may fix this problem.

![image](https://github.com/user-attachments/assets/23a1c564-1753-4706-a67c-e19a7a4c7dcf)

The same error pops up on the portable or installed application.

Let me know if you need more information.

Best regards,
Igor

**Comment by ophthalmos** [comment]
There is a new version (2.5.5.1) that detects additional error sources at this point and displays them as a message.
I'm looking forward to your feedback - what will be displayed now?

**Comment by MassShoes** [comment]
Now plays fine. Thank you for the quick response.
